apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lnpapp-ingress
  labels:
    app: lnp
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: example.com
    http:
      paths:
        - path: /lnp
          pathType: Prefix
          backend:
            service: 
              name: lnp-service
              port : 
                number : 8000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: lnpwebgui
              port: 
                number: 8080