apiVersion: v1
kind: Service
metadata:
  name: lnp-service
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30000
  - name: sip
    port: 5060
    targetPort: 5060
  - name: dns
    port: 53
    targetPort: 53  
  selector:
    app: lnpbackend
  type: LoadBalancer