apiVersion: apps/v1
kind: Deployment
metadata:
  name: lnpwebgui
  labels : 
    app: lnpwebgui
    tier: frontend
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: lnpwebgui
  template:
    metadata:
      labels:
        app: lnpwebgui
    spec:
      containers:
      - name: lnpwebgui
        image: haim9798/lnpwebgui:0.6
        imagePullPolicy: IfNotPresent
        name: lnpwebgui
        ports:
        - name: http
          containerPort: 80    
