apiVersion: v1
kind: Service
metadata:
  labels:
    app: lnpwebgui
  name: lnpwebgui
spec:
  ports:
  - nodePort: 30791
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: lnpwebgui
  sessionAffinity: None
  type: LoadBalancer

