apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-12-28T09:12:33Z"
  labels:
    app: lnpwebgui
  name: lnpwebgui
  namespace: default
  resourceVersion: "3825"
  uid: 38c5b7b4-3a83-42f8-a170-b21f8d571388
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.102.243.244
  clusterIPs:
  - 10.102.243.244
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30791
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: lnpwebgui
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
