apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2021-12-28T07:54:31Z","generation":2,"labels":{"app":"lnpwebgui"},"name":"lnpwebgui","namespace":"default","resourceVersion":"6007","uid":"db82b4e3-de04-4427-82f6-a659d91d696f"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"lnpwebgui"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"lnpwebgui"}},"spec":{"containers":[{"image":"docker.io/haim9798/general:lnpgui","imagePullPolicy":"IfNotPresent","name":"general","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2021-12-28T07:54:31Z"
  generation: 7
  labels:
    app: lnpwebgui
  name: lnpwebgui
  namespace: default
  resourceVersion: "339921"
  uid: db82b4e3-de04-4427-82f6-a659d91d696f
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: lnpwebgui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lnpwebgui
    spec:
      containers:
      - image: haim9798/lnpwebgui:0.6
        imagePullPolicy: IfNotPresent
        name: general
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2021-12-28T07:54:31Z"
    lastUpdateTime: "2022-01-02T08:12:15Z"
    message: ReplicaSet "lnpwebgui-555fc4b445" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-01-03T15:11:19Z"
    lastUpdateTime: "2022-01-03T15:11:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 7
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
