apiVersion: v1
kind: Service
metadata:
  name: redis-master
spec:
  selector:
    name: redis-master
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-replica
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis
  selector:
    name: redis-replica