apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-primary-deployment
  labels:
    name: redis-master
spec:
  replicas: 1 
  selector:
    matchLabels:
      name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      subdomain: primary
      containers:
      - name: redis
        image: redis
        command:
          - "redis-server"
        args:
          - "--protected-mode"
          - "no"
          - "--appendonly"
          - "yes"
        volumeMounts:
        - name: redis-data
          mountPath: /data 
        ports:
        - containerPort: 6379
      volumes:
      - name: redis-data
        hostPath:
          path: /home/docker/redis-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica-deployment
  labels:
    name: redis-replica
spec:
  replicas: 2 
  selector:
    matchLabels:
      name: redis-replica
  template:
    metadata:
      labels:
        name: redis-replica
    spec:
      subdomain: replica
      containers:
      - name: redis
        image: redis
        command:
          - "redis-server"
        args:
          - "--slaveof"
          - "redis-master.default.svc.cluster.local"
          - "6379"
          - "--protected-mode"
          - "no"   
        ports:
        - containerPort: 6379